steps:
- name: Set up Python
  uses: actions/setup-python@v3
  with:
    python-version: 3.8

- name: Copy requirements.txt
  run: cp .github/workflows/requirements.txt requirements.txt

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Run tests
  run: pytest

